{
 "title": "Ipfs content location",
 "time": { "from": "2022-03-21T00:00:00.000Z", "to": "2022-03-21T23:59:59.000Z" },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  continent AS metric,\n  count(cid) AS \"requests\"\nFROM requests\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1, continent,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  continent AS metric,\n  avg(request_time) AS \"requests\"\nFROM requests\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1, continent,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Request upstream latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  continent AS metric,\n  avg(upstream_time) AS \"requests\"\nFROM requests\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1, continent,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Requests Worldwide",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  country AS metric,\n  count(*) AS \"count\"\nFROM requests\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY country\norder by country"
    }
   ]
  },
  {
   "title": "Requests CIDs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct cid) as \"Distinct\"\nFROM requests r \nwhere $__timeFilter(\"timestamp\")\n"
    },
    {
     "rawSql": "SELECT\n  count(cid) as \"Total\"\nFROM requests r \nwhere $__timeFilter(\"timestamp\")\n"
    }
   ]
  },
  {
   "title": "Providers & content Worldwide",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.country AS metric,\n  count(p.cid) AS \"count\"\nFROM requests r join providers p on r.cid = p.cid\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\norder by 1"
    },
    {
     "rawSql": "SELECT\n  p.country AS metric,\n  count(distinct p.peerId) AS \"count\"\nFROM requests r join providers p on r.cid = p.cid\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1\norder by 1"
    }
   ]
  },
  {
   "title": "Providers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct peerId) as \"Providers\"\nFROM providers p join requests r on p.cid = r.cid\nwhere $__timeFilter(\"timestamp\")\n"
    }
   ]
  },
  {
   "title": "Provided CIDs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct p.cid) as \"Distinct\"\nFROM providers p join requests r on p.cid = r.cid\nwhere $__timeFilter(\"timestamp\")\n"
    },
    {
     "rawSql": "SELECT\n  count(p.cid) as \"Total\"\nFROM providers p join requests r on p.cid = r.cid\nwhere $__timeFilter(\"timestamp\")\n"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as \"All\"\nFROM requests\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(*) as \"With location\"\nFROM requests \nWHERE\n  $__timeFilter(\"timestamp\") and continent is not NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(*) as \"W/out location\"\nFROM requests\nWHERE\n  $__timeFilter(\"timestamp\") and continent is NULL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Providers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct p.peerId) as \"All\"\nFROM requests r join providers p on r.cid = p.cid\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(distinct p.peerId) as \"With location\"\nFROM requests r join providers p on r.cid = p.cid\nWHERE\n  $__timeFilter(\"timestamp\") and p.continent is not NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(distinct p.peerId) as \"W/out location\"\nFROM requests r join providers p on r.cid = p.cid\nWHERE\n  $__timeFilter(\"timestamp\") and p.continent is NULL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Locality Heatmap",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  r.continent as \"Requesters\",\n  p.continent as \"Providers\",\n  count(*) as \"Requests\"\nFROM requests r join Providers p on r.cid = p.cid\nWHERE\n  $__timeFilter(\"timestamp\") and r.continent is not Null and p.continent is not Null\ngroup by 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Requests to Provided Content",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  r.continent as \"Requesters\",\n  p.continent as \"Providers\",\n  count(*) as \"Requests\"\nFROM requests r join providers p on r.cid = p.cid\nWHERE\n  $__timeFilter(\"timestamp\")\ngroup by 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Requests by continent",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  continent as \"Requesters\",\n  count(*) as \"Requests\"\nFROM requests\nWHERE\n  $__timeFilter(\"timestamp\")\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Locality of CIDs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\n   $__timeGroupAlias(\"timestamp\",$__interval),\n   count(p.cid) as \"Local CIDs\"\nFROM requests r join providers p on r.cid = p.cid\nWHERE\n  $__timeFilter(\"timestamp\") and\n  r.continent = p.continent\ngroup by 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n   count(p.cid) as \"Non-Local CIDs\"\nFROM requests r join providers p on r.cid = p.cid\nWHERE\n  $__timeFilter(\"timestamp\") and\n  r.continent != p.continent\ngroup by 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Replica Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Replica CIDs",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.cid as \"Content\",\n  count(distinct p.peerId) as \"Replicas\"\nFROM providers p join requests r on p.cid = r.cid\nWHERE\n  $__timeFilter(\"timestamp\")\ngroup by 1\nORDER BY 2 desc"
    }
   ]
  },
  {
   "title": "Replica CID in the same region",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.cid as \"Content\",\n  count(distinct p.peerId) as \"Replicas\"\nFROM providers p join requests r on p.cid = r.cid\nWHERE\n  $__timeFilter(\"timestamp\") and p.continent = r.continent\ngroup by 1\nORDER BY 2 desc"
    }
   ]
  },
  {
   "title": "Replica CID outside region",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.cid as \"Content\",\n  count(distinct p.peerId) as \"Replicas\"\nFROM providers p join requests r on p.cid = r.cid\nWHERE\n  $__timeFilter(\"timestamp\") and p.continent != r.continent\ngroup by 1\nORDER BY 2 desc"
    }
   ]
  }
 ]
}