version: "3.9"

services:
  parser:
    deploy:
      replicas: 1
    image: pedro_akos/ipfs-gateway-logs-parser:0.1a-patched
    build:
      context: .
      dockerfile: dockerfiles/parser_service.dockerfile
      args:
        - MAXMIND_LICENCE_KEY=${MAXMIND_LICENCE_KEY}

  find_providers:
    image: pedro_akos/ipfs-find-providers:0.1
    deploy:
      mode: replicated
      replicas: 1
    build:
      context: .
      dockerfile: dockerfiles/find_providers_service.dockerfile

  db:
    image: pedro_akos/ipfs-gateway-logs-db:0.2
    shm_size: 4g
    tmpfs:
      - /tmp:size=4g
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    ports:
      - 5433:5432
    build:
      context: .
      dockerfile: dockerfiles/postgres_db.dockerfile

  web:
    image: pedro_akos/ipfs-gateway-logs-web:0.1
    build:
      context: .
      dockerfile: dockerfiles/nginx_web.dockerfile
    ports:
      - 6098:80



  dashboard:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3001:3000
    links:
      - db

  broker:
    image: rabbitmq:latest
    ports:
      - 5672:5672

  writer:
    image: pedro_akos/ipfs-content-location-writer:0.1
    build:
      context: .
      dockerfile: dockerfiles/write_find_provider_logs_to_db.dockerfile
    depends_on:
      - db
      - broker
      - parser
    links:
      - parser
      - broker
      - db
    restart: unless-stopped
    deploy:
      replicas: 1

  controller:
    image: pedro_akos/ipfs-content-location-controller:0.1
    command:
      - "--concurrency"
      - "200"
      - "--batch"
      - "100"
    build:
      context: .
      dockerfile: dockerfiles/controller.dockerfile
    depends_on:
      - db
      - broker
      - find_providers
      - parser
    links:
      - parser
      - find_providers
      - broker
      - db
    restart: unless-stopped
    deploy:
      replicas: 1


volumes:
  db-data:
  grafana-storage:
